<?php
/**
 * hook_entity_view
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_entity_view/7.x
 */
function mtt_entity_view($entity, $type) {
  if ($type != 'menu_fields' || !request_path()) {
    return;
  }

  $path = explode("/", request_path());
  $link = menu_link_load($entity->mlid);

  $entity->content['#prefix'] = '<li class="element-invisible" aria-hidden="true">';

  foreach ($entity->tags['und'] as $item) {
    $term  = taxonomy_term_load($item['tid']);
    $corso = $term->name;
    
    if ($corso === $path[0]) { 
      $entity->content['#prefix'] = '<li' . drupal_attributes($entity->content['menu_fields_link'][$link['mlid']]['#attributes']) . '>';
    }
  }
}

/**
 * hook_form_alter
 * https://api.drupal.org/api/drupal/modules%21system%21system.api.php/function/hook_form_alter/7.x
 */
function mtt_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id != 'menu_edit_item') {
    return;
  }

  $form['menu_fields']['#collapsible']              = FALSE;
  $form['menu_fields']['enabled']['#default_value'] = TRUE;
}





